version: '3'
services:
  db:
    image: db_img
    ports:
    - "3306:3306"
  web:
    build: .
    expose:
    - "8080"
    environment:
    - DATABASE_HOST=db
    depends_on:
    - db
    